### ISSUE TITLE
PaddleOCR 检测模型部署问题

### ISSUE THREAD

**Issue by LiQiang0307** [PaddlePaddle/FastDeploy#1759]
## 环境

- 【FastDeploy版本】：  fastdeploy-gpu-python-1.0.1
- 【系统平台】:  Windows x64(Windows10)
- 【硬件】：TITAN X ， CUDA 11.3 CUDNN 8.2
- 【编译语言】：Python3.8

PaddleOCR检测模型训练配置文件：
```
Global:
  use_gpu: true
  use_xpu: false
  use_mlu: false
  epoch_num: 150
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/db_mv3_0331/
  save_epoch_step: 30
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 200]
  cal_metric_during_train: False
  pretrained_model: ./pretrain_models/MobileNetV3_large_x0_5_pretrained
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0001
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:/paddleocr/PaddleOCR-release-2.6/train_data/0330/
    label_file_list:
      - D:/paddleocr/PaddleOCR-release-2.6/train_data/0330/train_0330_Label.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [640, 640]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 4
    num_workers: 1
    use_shared_memory: True

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:/paddleocr/PaddleOCR-release-2.6/train_data/0330/
    label_file_list:
      - D:/paddleocr/PaddleOCR-release-2.6/train_data/0330/test_0330_Label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 1
    use_shared_memory: True
```

使用训练模型预测可以正常检测出文字所在位置：
```
python3 tools/infer_det.py -c configs/det/det_mv3_db.yml -o Global.infer_img="./doc/imgs_en/" Global.pretrained_model="./output/det_db/best_accuracy"
```

使用下面命令进行模型导出后，推理预测结果为空，无法检测到文字位置。
导出命令：
```
python3 tools/export_model.py -c configs/det/det_mv3_db.yml -o Global.pretrained_model="./output/det_db/best_accuracy" Global.save_inference_dir="./output/det_db_inference/"
```
推理命令：
```
python3 tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/det_db_inference/" --image_dir="./doc/imgs/" --use_gpu=True
```

在推理命令中添加`--det_limit_type="resize_long"` 可以正常检测。
```
python3 tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./output/det_db_inference/" --image_dir="./doc/imgs/" --use_gpu=True  --det_limit_type="resize_long"
```

问题：如何在Fastdeploy中加载--det_limit_type="resize_long"命令或者如何导出模型使Fast deploy能够进行推理？
