### ISSUE TITLE
vehicle_attribute_model 模型报错

### ISSUE THREAD

**Issue by dwdcth** [PaddlePaddle/FastDeploy#872]
## 环境

- FastDeploy版本： 说明具体的版本，如fastdeploy-windows-cpu-1.0.0
- 系统平台:  Windows x64(Windows10)
- 编译语言： Python(3.10）

## 问题描述
代码：
```python
import cv2
import fastdeploy.vision as vision

# 使用的这个模型  
# https://bj.bcebos.com/v1/paddledet/models/pipeline/vehicle_attribute_model.zip

base = 'some_path/vehicle_attribute_model'
model = vision.classification.PPLCNet(f"{base}/model.pdmodel",
                                 f"{base}/model.pdiparams",
                                 f"{base}/infer_cfg.yml")

# 图片 https://raw.githubusercontent.com/PaddlePaddle/PaddleClas/release/2.4/deploy/images/PULC/vehicle_attribute/0002_c002_00030670_0.jpg

im = cv2.imread(f"{base}/00che.jpeg")
result = model.predict(im.copy())
print(result)


vis_im = vision.vis_detection(im, result, score_threshold=0.5)
cv2.imwrite("vis_image.jpg", vis_im)
```

报错如下：

```
fastdeploy\vision\classification\ppcls\__init__.py", line 97, in predict
    return self._model.predict(im)
RuntimeError: [ PARAMETER_MISMATCH ] Failed to set input blob with precision: U8, if CNNNetwork input blob precision is: FP32
```

**Comment by jiangjiajun** [comment]
将infer_cfg.yml上传一下

**Comment by dwdcth** [comment]
```
mode: paddle
draw_threshold: 0.5
metric: ATTR
use_dynamic_shape: false
arch: PPLCNet
min_subgraph_size: 5
Preprocess:
- keep_ratio: false
  target_size:
  - 192
  - 256
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
label_list: 
- color
- type

```
